### ISSUE TITLE
No dot? :point_right: :point_left: 

### ISSUE THREAD

**Issue by pawamoy** [pi0/config-dir#13]
Sometimes I wish we would stop using dots in front of the name of files or directories that are tracked and important to a repository. I understand dotfiles in the home folder, where you want a good UX, hiding all these weird stuff by default, but in a repository, I don't see any benefit to using dotfiles, except for super special stuff (`.git` and other Git stuff) and things that should definitely be hidden and Git-ignored (`.cache`, all other cache folders, build artifacts, `.venv`, etc.).

So... how about `config` instead of `.config`? :grinning:

**Comment by pawamoy** [comment]
Ha, sorry, already discussed in #1, closing :sweat_smile:

**Comment by pi0** [comment]
Hey. I have no hard feelings honestly. Maybe we could find a way to make it customizable with `.config/ -> config/` link (or a `.config` file with `./config`)? Feel free to make new discussion or continue on existing one re naming ideas 👍🏼
