### ISSUE TITLE
Document why a command line parameter specifying "custom" config location does not cut it

### ISSUE THREAD

**Issue by scop** [pi0/config-dir#18]
A number of RFE's related to supporting loading .config has been met with counterarguments noting that those tools have a command line option or an environment variable for specifying a custom path to the config file if the defaults are not satisfactory.

Would be good to document in README.md why such a cmdline option or env var is not enough -- basically because the tools can be invoked from various contexts such as different IDEs, (git) commit hook managers, plain cmdline run, etc etc, and all those have different ways to configure their tools' command line options and environment variables. Thus it's not feasible without prescribing the "supported" contexts, and prescribing them is not nice.

**Comment by pi0** [comment]
Good point. Would you like to draft a PR to add an explanation? 🙏🏼

**Comment by scop** [comment]
Done, https://github.com/pi0/config-dir/pull/19
